### PR TITLE
fix stopping stream if it is active when using `getDevice`

### LINKED ISSUE #561: Safeguard against a potential resource leak(media streams) due to user missuse
## Description 
Users improperly using videojs-record with external triggers(user defined buttons) might call 
 `player.record().getDevice();` multiple times before trying to use `stopDevice()`.
In this case multiple media streams would get created but only the last one would be freed when calling `stopDevice()`
The implication would be that the webcam would remain on even after `stopDevice()` is called.
 
## When would this situation be encountered?
```
Eg: let's say the user creates an external button "start webcam" which calls getDevice, 
but doesn't handle thoroughly the state of the system to see if it is actually ok to call getDevice. 
Someone visiting the website might press that button multiple times 
(maybe he doesn't notice the the request for video/audio permissions) after the first press.
``` 

## Potential way to add an extra safeguard

Before 
```
//videojs.record.js
value: function onDeviceReady(stream) {
....
// At this point this.stream could already be initialized,
// if the user didn't properly dispose of it the resource would never be released.
// ( the webcam would remain on after player.record().stopDevice() ).
this.stream = stream;
```
With a safeguard things could look something like:
```
//videojs.record.js
value: function onDeviceReady(stream) {
....
 if stream_is_initialized(this) {
    this.stream.getTracks().forEach(track => track.stop());
}
this.stream = stream;
```

### PR DESCRIPTION
**Pull request by bmsan**
fixes #561

### CODE REVIEW

**Review by thijstriemstra — CHANGES_REQUESTED** [review]
thanks! there are some trailing spaces, see https://github.com/collab-project/videojs-record/pull/562/files

**Comment by thijstriemstra** [comment]
Does this stop call introduce any flickering in the video preview stream?

**Comment by bmsan** [comment]
I ran two types of tests described below:
```
Test1: In change-video-input with 2 webcams connected, change fast the input device two times(before the webstream starts to get streamed).
Test2: Call getDevice() multiple times( I called this from the browser console
   eg: `player.record().getDevice(); player.record().getDevice()`
```
For both tests flickering is observed but in both  pre-pull request and post-pull request versions. But I don't think there is any extra flickering induced by this change.

More exactly for Test1 if you select very fast camera2 & then camera1 =>  camera2 will be seen for a fraction of a second, then background color, then camera1.

**Review by thijstriemstra — APPROVED** [review]
thanks!

**Pull request merged**
