### PR TITLE
Add missing file info for timestamp blobs

### LINKED ISSUE #206: Missing filename in timestamp blobs
## Description
Hello.
I noticed a difference between the two browsers.
I have a system Ubuntu 17.10 (64).

## Steps to reproduce
In the browser Chromium, everything works perfectly.
But an error in the Firefox browser when loading chunks

### Expected
Should have loaded 4 pieces of 500 kB each.

### Actual
Upload timestamp error:
Only the first 313 bytes of the first piece are loaded.

### Error output
    [Data] => Array
        (
            [name] => 
            [type] => 
            [tmp_name] => 
            [error] => 4
            [size] => 0
        )

## Additional Information
JS:

    var player = videojs("myVideo", {
        controls: true,
        width: 430,
        height: 240,
        fluid: false,
        plugins: {
            record: {
                audio: true,
                video: true,
                maxLength: 10,
                debug: true,
                // fire the timestamp event every 2 seconds
                timeSlice: 2000
            }
        }
    }, function () {
        // print version information at startup
        videojs.log('Using video.js', videojs.VERSION,
            'with videojs-record', videojs.getPluginVersion('record'),
            'and recordrtc', RecordRTC.version);
    });

    var segmentNumber = 0;

    player.on('timestamp', function() {
        if (player.recordedData && player.recordedData.length > 0) {
            var binaryData = player.recordedData[player.recordedData.length - 1];
            segmentNumber++;
            var formData = new FormData();
            formData.append('SegmentNumber', segmentNumber);
            formData.append('Data', binaryData);
            $.ajax({
                url: 'https://api.vide.me/rec/savem/',
                method: 'POST',
                data: formData,
                cache: false,
                processData: false,
                contentType: false,
                success: function (res) {
                    console.log("segment: " + segmentNumber);
                    $("#result-new-video").append("<p>" + res + "</p>");
                }
            });
        } else {
                console.log("No video: " + player.recordedData);
        }
    });

PHP:

    $fileName = $_POST["SegmentNumber"];
    $uploadDirectory = '/tmp/' . $fileName;
    if (!move_uploaded_file($_FILES["Data"]["tmp_name"], $uploadDirectory)) { // Work!
        echo("tmp_name problem moving uploaded file");
    }

#### videojs
VIDEOJS: Using video.js 6.6.2 with videojs-record 2.1.0 and recordrtc 5.4.7
#### browsers
Firefox 58.0.2 (64)
#### OSes
Ubuntu 17.10 64

### PR DESCRIPTION
**Pull request by thijstriemstra**
fixes #206

### CODE REVIEW

**Comment by SergeyKozlov** [comment]
Thanks, @thijstriemstra it really works.
I'm getting a small error:


This error does not affect the main functions.

**Comment by thijstriemstra** [comment]
@SergeyKozlov thanks for testing. I got rid of that error I think and committed the fix in https://github.com/collab-project/videojs-record/commit/939ce7cfed9af1f5f909cf4cc31ce8ce6858cd26 to the master branch. Can you see if the error is gone?

I would suggest to rely on the (new) `lastModified` property instead from now on, `lastModifiedDate` is [deprecated](https://developer.mozilla.org/en-US/docs/Web/API/File/lastModified). I left it in there but will remove it at some point.

**Comment by thijstriemstra** [comment]
Now that `lastModified` is fixed, a new, (previously masked) error about `name` appears:

blob-name

I'll take a look at this as well.

**Comment by thijstriemstra** [comment]
@SergeyKozlov I sometimes see a `File` object being created (without a `name` property), but most of the time it's a `Blob`, haven't figured why/where that happens.

**Comment by thijstriemstra** [comment]
fyi, I released v2.1.1 with the fixes just now.

**Comment by SergeyKozlov** [comment]
Thank you @thijstriemstra .

I use PHP in my project.
For this I use the following files:


After the new installation, the plugin folder became different:
Before:


After:


And I had a mistake:


What files should I copy to my server?

**Comment by thijstriemstra** [comment]
@SergeyKozlov take a look at the script tags for the various scripts, and the order you should include them, in the examples: https://github.com/collab-project/videojs-record/blob/master/examples/audio-video.html#L7

**Pull request merged**
