### PR TITLE
Fix firefox playback

### PR DESCRIPTION
**Pull request by savayg**
I experienced the same firefox issue, this fixed it. Didn't have time to test all your demo files though

### CODE REVIEW

**Comment by thijstriemstra** [comment]
Thanks @savayg. What version(s) of Firefox did you test this on? What video.js version?

**Comment by savayg** [comment]
Video.js 5.13.0, Firefox 46.0.1

**Comment by thijstriemstra** [comment]
Thanks, hopefully @ignl can give this a try as well.

**Comment by ignl** [comment]
I could not reproduce the error anymore so I haven't tested PR. @savayg can you still reproduce an error without your fix? What version of recordrtc do you use? Could you try to update firefox and check if you can still reproduce it? Same with recordrtc. I updated to newest versions and preliminary it seems that this problem is gone for me (need a bit more testing though).

**Comment by thijstriemstra** [comment]
@savayg what version of recordrtc are you using? what OS?

**Comment by thijstriemstra** [comment]
I cannot reproduce this with video.js 5.13.0 on OSX Firefox 46.0.1 or Firefox 49.0.

**Comment by thijstriemstra** [comment]
Closing because there's no feedback. Reopen with more info as requested.

**Pull request closed without merging**
