### PR TITLE
add image-only output options

### PR DESCRIPTION
**Pull request by thijstriemstra**
refs #400

### CODE REVIEW

**Comment by vendramini** [comment]
@thijstriemstra is everything ok here? Should I do something with my PR now? What do we need to have this feature released?

Your comment on my PR https://github.com/collab-project/videojs-record/pull/400

> Can you update your PR with this and implement the rest (e.g. documentation, defining actual vars in loadOptions etc).

Still needed?

**Comment by thijstriemstra** [comment]
> @thijstriemstra is everything ok here? Should I do something with my PR now? What do we need to have this feature released?

Can you test this pull request?

**Comment by vendramini** [comment]
Sure, manually, you mean?

I've a doubt: what do you think if the new attributes `imageOutputType`, `imageOutputFormat` and `imageOutputQuality` was added within `image` property? Like
```javascript
record: {
    image: {
        outputType: 'dataURL',
        quality: 1,
        format: 'image/png'
    }
}
```
Or do you have some reason to add outside?

**Comment by vendramini** [comment]
I've created the test, added some docs here https://github.com/collab-project/videojs-record/pull/422
I don't know if I did the correct git flow process, it's my first time collaborating in a project.

**Comment by thijstriemstra** [comment]
Sorry for the delay. Looks good to me, thanks for the help!

**Pull request merged**
