### PR TITLE
Fix for IMAGE_ONLY mode - stretched output in player

### PR DESCRIPTION
**Pull request by johnfslattery**
Hi @thijstriemstra,

I've had a go at putting together a fix for the following issue that I opened some weeks ago:

#511 - IMAGE_ONLY mode - can't specify camera resolution and stretched output. 

I have created a method captureCameraFrame() that draws the full resolution image onto a different canvas from recordCanvas and resolves that. The image is also drawn onto recordCanvas scaled to fit the image to the player for preview purposes. The aspect ratio of the image is maintained.

I opted to not edit the existing captureFrame() method because it was unclear what interaction that has with ANIMATION_ONLY mode. Incidentally, the preview in ANIMATION_ONLY mode does not work in my local code or the online demos.

If you have any amendments, feedback or further comments, I would love to hear them.

Kind Regards,
John

### CODE REVIEW

**Comment by johnfslattery** [comment]
@thijstriemstra , Apologies allow me to amend (and lint this time).

**Review by thijstriemstra — CHANGES_REQUESTED** [review]
thanks @johnfslattery I see a lot of duplicated code, we should try to eliminate that.

> I opted to not edit the existing captureFrame() method because it was unclear what interaction that has with ANIMATION_ONLY mode.

GIF mode is broken should be removed, or improved, at some point, I wouldn't worry about it too much.

> Incidentally, the preview in ANIMATION_ONLY mode does not work in my local code or the online demos.

Again, please minimize the changes (inc. the uncessary code formatting changes).

Thanks!

**Comment by johnfslattery** [comment]
Hi @thijstriemstra,

I've had a go at cleaning it up and removing duplicate code/unnecessary formatting changes. I opted to leave the original captureFrame() and captureCameraFrame() separate as the dimension of the returned canvas is a different dimension to the player. I hope this is ok?

Thanks,
J

**Comment by thijstriemstra** [comment]
>  I opted to leave the original captureFrame() and captureCameraFrame() separate as the dimension of the returned canvas is a different dimension to the player. I hope this is ok?

I think we should use the original canvas, because setting the canvas dimensions to the size of the player was a mistake/bug, and we should correct that. 

I like your approach but I reworked your original code into a new branch, see https://github.com/collab-project/videojs-record/tree/image-stretch-511

@johnfslattery could you give that a try?

**Comment by thijstriemstra** [comment]
Closing in favor of #556

**Pull request closed without merging**
