### PR TITLE
ffmpeg.js plugin

### LINKED ISSUE #366: Record as WAV and convert to WEBM
I was wondering if it's possible to record as WAV and have the WAV blob available in recordedData, whilst as the same time having access to the audio as WEBM in the convertedData?

The reasons for this are because I need WAV which I upload to a server via a worker, but I also need WEBM so I can immediately play the audio in Wavesurfer-js.

WAV isn't seekable in Chrome so the user can't jump around the file properly, WEBM does allow this but I can't upload a WEBM file because the application receiving the file doesn't recognise WEBM.

### PR DESCRIPTION
**Pull request by thijstriemstra**
This PR introduces a 'converter' plugin using [ffmpeg.js](https://github.com/Kagami/ffmpeg.js) that converts the recorded data into other audio/video file formats using a port of ffmpeg for the browser.

fixes #366

### CODE REVIEW

**Comment by wayne530** [comment]
Just curious if there is any update on the progress here? Happy to help test/troubleshoot :)

**Comment by thijstriemstra** [comment]
@wayne530 yes it should work, just needs a bit of refactoring. Testing this PR is always welcome!

**Comment by shealan** [comment]
Is this finished? Trying to work out if its just tests failing or if there is some work left to do... Can't wait to try it out! :)

**Comment by thijstriemstra** [comment]
@shealan checkout the branch, build and test the example.

**Comment by thijstriemstra** [comment]
This plugin will be available in the upcoming v3.8.0 release @wayne530 @shealan

**Comment by shealan** [comment]
@thijstriemstra thank you! :)

**Pull request merged**
